window.KRILLION_PROMPTS = [
    { category: "California", text: "Name a city in California.", answers: { "los angeles": ["Los Angeles", 4], "san diego": ["San Diego", 8], "san francisco": ["San Francisco", 8], "sacramento": ["Sacramento", 16], "fresno": ["Fresno", 32], "eureka": ["Eureka", 64], "tehachapi": ["Tehachapi", 100], "bakersfield": ["Bakersfield", 16], "monterey": ["Monterey", 32], "redding": ["Redding", 64], "oakland": ["Oakland", 16], "anaheim": ["Anaheim", 16] } },
    { category: "Ocean life", text: "Name an animal that lives in the ocean.", answers: { "dolphin": ["Dolphin", 4], "shark": ["Shark", 4], "whale": ["Whale", 8], "octopus": ["Octopus", 16], "sea turtle": ["Sea turtle", 16], "jellyfish": ["Jellyfish", 16], "narwhal": ["Narwhal", 32], "manta ray": ["Manta ray", 32], "coelacanth": ["Coelacanth", 64], "vampire squid": ["Vampire squid", 100], "goblin shark": ["Goblin shark", 64], "mola mola": ["Mola mola", 100] } },
    { category: "Space", text: "Name a moon in our solar system.", answers: { "moon": ["The Moon", 4], "luna": ["The Moon", 4], "europa": ["Europa", 16], "titan": ["Titan", 8], "io": ["Io", 16], "ganymede": ["Ganymede", 32], "enceladus": ["Enceladus", 32], "triton": ["Triton", 32], "phobos": ["Phobos", 64], "deimos": ["Deimos", 64], "miranda": ["Miranda", 64], "hyperion": ["Hyperion", 100] } },
    { category: "Fruit", text: "Name a fruit that has a pit.", answers: { "peach": ["Peach", 4], "cherry": ["Cherry", 8], "avocado": ["Avocado", 8], "plum": ["Plum", 16], "mango": ["Mango", 8], "apricot": ["Apricot", 32], "nectarine": ["Nectarine", 32], "olive": ["Olive", 16], "lychee": ["Lychee", 64], "date": ["Date", 32], "loquat": ["Loquat", 100], "santol": ["Santol", 100] } },
    { category: "Landmarks", text: "Name a famous tower.", answers: { "eiffel tower": ["Eiffel Tower", 4], "leaning tower of pisa": ["Leaning Tower of Pisa", 8], "big ben": ["Big Ben", 8], "tokyo tower": ["Tokyo Tower", 16], "cn tower": ["CN Tower", 16], "space needle": ["Space Needle", 16], "blackpool tower": ["Blackpool Tower", 32], "hercules tower": ["Tower of Hercules", 64], "hercules": ["Tower of Hercules", 64], "galata tower": ["Galata Tower", 32], "abraj al bait": ["Abraj Al Bait", 64], "qutb minar": ["Qutb Minar", 100] } },
    { category: "Birds", text: "Name a bird that cannot fly.", answers: { "ostrich": ["Ostrich", 4], "penguin": ["Penguin", 4], "kiwi": ["Kiwi", 16], "emu": ["Emu", 8], "cassowary": ["Cassowary", 32], "rhea": ["Rhea", 32], "kakapo": ["Kakapo", 64], "takahe": ["Takahe", 100], "weka": ["Weka", 64], "steamer duck": ["Steamer duck", 100], "dodo": ["Dodo", 8] } },
    { category: "Trees", text: "Name a tree that grows in cold climates.", answers: { "pine": ["Pine", 4], "spruce": ["Spruce", 8], "birch": ["Birch", 8], "fir": ["Fir", 8], "willow": ["Willow", 16], "larch": ["Larch", 32], "aspen": ["Aspen", 16], "tamarack": ["Tamarack", 64], "rowan": ["Rowan", 32], "mountain ash": ["Mountain ash", 32], "arctic willow": ["Arctic willow", 100], "dahurian larch": ["Dahurian larch", 100] } },
    { category: "Instruments", text: "Name a string instrument.", answers: { "guitar": ["Guitar", 4], "violin": ["Violin", 4], "cello": ["Cello", 8], "harp": ["Harp", 8], "banjo": ["Banjo", 16], "ukulele": ["Ukulele", 16], "mandolin": ["Mandolin", 32], "erhu": ["Erhu", 64], "koto": ["Koto", 32], "nyckelharpa": ["Nyckelharpa", 100], "hardingfele": ["Hardingfele", 100], "sitar": ["Sitar", 16] } },
    { category: "World capitals", text: "Name a capital city in South America.", answers: { "lima": ["Lima", 4], "bogota": ["Bogota", 8], "santiago": ["Santiago", 8], "quito": ["Quito", 16], "caracas": ["Caracas", 16], "asuncion": ["Asuncion", 32], "sucre": ["Sucre", 64], "paramaribo": ["Paramaribo", 64], "georgetown": ["Georgetown", 32], "brasilia": ["Brasilia", 8] } },
    { category: "Insects", text: "Name an insect with iridescent wings.", answers: { "butterfly": ["Butterfly", 4], "dragonfly": ["Dragonfly", 8], "morpho butterfly": ["Morpho butterfly", 16], "jewel beetle": ["Jewel beetle", 32], "cicada": ["Cicada", 16], "damselfly": ["Damselfly", 32], "blue dasher": ["Blue dasher", 64], "jewelwing": ["Jewelwing", 64], "rainbow scarab": ["Rainbow scarab", 100], "metallic wood boring beetle": ["Metallic wood-boring beetle", 100] } }
];